Repository cap-collectif/ui, pull requests merged in 2022-04, with the labels that each got.

#246 [19] Radio component
  src/components/form/index.ts
  src/components/form/radio/Radio.stories.tsx
  src/components/form/radio/Radio.style.tsx
  src/components/form/radio/Radio.tsx
  src/components/form/radio/RadioGroup.stories.tsx
  src/components/form/radio/RadioGroup.tsx
  src/components/form/radio/index.ts
Labels: Component

#247 v1.1.0
  CHANGELOG.md
  package.json
Labels: Release

#250 Export `useMultiStepModal`from `MultiStepModal`
  src/components/multiStepModal/index.tsx
Labels: Form

#251 v1.1.2
  CHANGELOG.md
  package.json
Labels: Release

#254 `MultiStepModal` pass context actions as props to children
  src/components/multiStepModal/MultiStepModal.tsx
  src/components/multiStepModal/footer/MultiStepModal.Footer.ContinueButton.tsx
  src/components/multiStepModal/index.tsx
Labels: Improvement

#257 [33] Search with suggestions
  src/components/search/Search.stories.tsx
  src/components/search/Search.tsx
Labels: Component

#259 v1.2.0
  CHANGELOG.md
  package.json
Labels: Release
